markdown: kramdown
collections_dir: my_collections
# Notlarında Yer Alıyordu, Serbest Düşünce Akışı, Karanlık Sanatlara Karşı Savunma Dersi.
title: Tozbulut - Gezegendeki Olası Hayatlardan Birinin Bir Tarifnamesi
description: > # this means to ignore newlines until "baseurl:"
  Gezegendeki Olası Hayatlardan Birinin Bir Tarifnamesi
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://tozbulut.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
